---
- name: Install Apache Tomcat10 using ansible
  hosts: tomcat
  become: true
  tasks:
    - name: Update the System Packages
      apt:
        upgrade: yes
 
    - name: Install JAVA
      apt:
        name: openjdk-11-jre-headless
        state: present
